### ISSUE TITLE
AttributeError: Requirements instance has no attribute 'requirements'

### ISSUE THREAD

**Issue by menzenski** [socketubs/requirements#4]
I'm using [cookiecutter](https://github.com/audreyr/cookiecutter-pypackage) to create a Python package and would like to use `requirements.py` to handle package dependencies. I'm using Python 2.7.11 (with Anaconda 2.2.0).

I've got `requirements.txt` and `requirements.py` in my package's root directory, and my `setup.py` contains the lines

``` Python
from requirements import r
...
setup(
    ...
    **r.requirements,
    ...
)
```

When I try to run `python setup.py develop`, I get an AttributeError: `Requirements instance has no attribute 'requirements'`.

**Comment by menzenski** [comment]
Calling `**r.dependencies` instead seems to work.

**Comment by toxinu** [comment]
Sorry for being late. This is little mistake in README of course.
Maybe both of properties (requirements and dependencies) can be used to avoid this confusion.
